name: Install helm chart

on:
  repository_dispatch:
    types: [backend_updated, frontend_updated]

jobs:
  helm:
    name: Helm lint and release
    runs-on: ubuntu-latest
    needs: push_to_registry

    steps:
      - uses: actions/checkout@v2
      - name: Helm Lint
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ./helm-chart
      - name: Helm install
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade --install conduit ./helm-chart
          kubeconfig: '${{ secrets.KUBECONFIG }}'